steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'

- script: |
    cat > .env.js <<EOF
    module.exports = {
      ROLLBAR_POST_SERVER_ITEM_ACCESS_TOKEN: '$(ROLLBAR_POST_SERVER_ITEM_ACCESS_TOKEN)',
      ROLLBAR_POST_CLIENT_ITEM_ACCESS_TOKEN: '$(ROLLBAR_POST_CLIENT_ITEM_ACCESS_TOKEN)',
      FIREBASE_SERVICE_ACCOUNT: '$(FIREBASE_SERVICE_ACCOUNT)'
    };
    EOF

- script: |
    npm install --legacy-peer-deps
    npm run build